### ISSUE TITLE
Wording around existing keys

### ISSUE THREAD

**Issue by ohdns** [mozilla/wikimo_content#103]
`Existing keys are generally stored in ~/.ssh/ (Linux/OSX) or %APPDATA% (Windows). Look for id_{rsa,ed25519,ecdsa,dsa}, or legacy identity files.`

Please consider rewording, as folks sometimes generate custom keys and reference them using `IdentityFile`.  Folks will miss many keys if auditing only id_ prefixed keys.  A case-insensitive search for `IdentityFile` in /home/*/.ssh/config (or wherever their home dirs reside) will expose some of them.

I am currently trying to write a simple shell script to find all of these files and put their sig from `ssh-keygen -lf` of the keys and authorized_keys into Splunk so that I can report on the account-system trust mapping, as any user can trust any users keys.

**Comment by gdestuynder** [comment]
there are now more file name as well for example when using certificate based authentication

**Comment by ohdns** [comment]
Thankyou for updating.
