### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/wikimo_content#136]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/wikimo_content/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by SpikeUK** [comment]
Is this relevant to WMO?

**Comment by gene1wood** [comment]
I've disabled the wiki as it wasn't used and added the restriction just in case.

> Is this relevant to WMO?

The wiki Hal's talking about here is the GitHub wiki on this GitHub repo (not wiki.mozilla.org which has content derived from this repo's Git content (not it's GitHub wiki)
