### ISSUE TITLE
ssh key generation instructions are incomplete

### ISSUE THREAD

**Issue by jruderman** [mozilla/wikimo_content#15]
https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Key_generation puts the date in our primary key and asks us to create other keys. But ssh doesn't pick up keys with non-default names!

https://help.github.com/articles/error-permission-denied-publickey/ suggested using "ssh add", but that only lasts until reboot (at least on Mac).

On IRC, kang suggested adding an "IdentityFile" line in ~/.ssh/config, which seems like a better solution. He suggested configuring ssh to only try the key for specific hosts, but it wasn't clear to me whether this has a security benefit over just adding the key globally.

**Comment by floatingatoll** [comment]
Note that on OS X, using 'ssh-add -K' stores the password to the key being
added in your OS X keychain, providing an alternative to IdentityFile.

**Comment by gdestuynder** [comment]
multiple keys depending on their use case help segmenting accesses, specially if stored on separate devices
For example you may have your personal key (generally ~/.ssh/id_rsa) on your computer and copied to your work laptop or mozilla laptop.
then you add a mozilla-specific key (~/.ssh/id_rsa_mozilla for example). this wont be picked up by default
You can have an identityfile specified in the configuration for, say, *.mozilla.com and *.mozilla.org

If your personal key has been copied/used on personal computers and is compromised this wont affect mozilla accounts.
