### ISSUE TITLE
Add section on SQL Injection to the Web Security guidelines

### ISSUE THREAD

**Issue by marumari** [mozilla/wikimo_content#33]
I had thought about it for the first release, but I didn't want to be too ambitious.

**Comment by amuntner** [comment]
Updating the Secure Coding Guidelines is one of my quarterly goals, I'll invite you as a reviewer later of you'd like. I'm losing this bug, we'll cover the topic in the guidelines.

**Comment by marumari** [comment]
Sounds great.
