### ISSUE TITLE
Check to see if there are remote changes with git before sync

### ISSUE THREAD

**Issue by marumari** [mozilla/wikimo_content#51]
Add a sanity check in sync.py that will refuse to sync if there are upstream changes that haven't been pulled down.

**Comment by gdestuynder** [comment]
PR welcome : D

Maybe instead it should issue a warning with a prompt no matter what content is pushed - because it cannot know what the upstream repository is (well, it can be hardcoded but thats hackish)

**Comment by gdestuynder** [comment]
Found a nicer way by doing a direct pull:

> Page Security/Risk_management differ.
From https://github.com/mozilla/wikimo_content
 * branch            master     -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
Traceback (most recent call last):
  File "./sync.py", line 141, in <module>
    main(opts, args)
  File "./sync.py", line 122, in main
    compare_site_and_disk(config, diff, site, docs, push, get)
  File "./sync.py", line 88, in compare_site_and_disk
    check_repos_is_current(config)
  File "./sync.py", line 54, in check_repos_is_current
    raise Exception("Operation cancelled: Failed to update from upstream repository. Check you have the latest version of the wiki checked-out  before attempting to push again.")
Exception: Operation cancelled: Failed to update from upstream repository. Check you have the latest version of the wiki checked-out  before attempting to push again.

**Comment by gdestuynder** [comment]
https://github.com/mozilla/wikimo_content/pull/53

**Comment by gdestuynder** [comment]
Fixed by pull request 53
