### ISSUE TITLE
Add minimal Flask/nginx/gunicorn/Django app that meets all expectations

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/wikimo_content#70]
This would go a long way to informing how to meet the criterion.  It can be used as a blackbox to get test concrete responses, and the code can be used to learn how to implement the required features.

**Comment by gdestuynder** [comment]
I suspect this is about the openidc page, in which case I would direct you to https://github.com/mozilla-iam/testrp.security.allizom.org/issues (which is already linked in the doc)

I'm going to close the comment here so that you can open it there if you would like to
