### ISSUE TITLE
OpenSSH guidelines: Diffie-Hellman group modulo size

### ISSUE THREAD

**Issue by David-5-1** [mozilla/wikimo_content#75]
I am surprised not to see any note on the fact `/etc/ssh/moduli` may contain weak DH groups to be used when key exchange algorithm is `diffie-hellman-group-exchange-sha256` (or `diffie-hellman-group-exchange-sha1` although it is discouraged). Unfortunately, configuration for this can only be done on server side as far as I know (since no client I know of allows to choose the size ; although the protocol requires the client to announce supported sizes). Using Debian jessie default configuration, I end up having modules in `/etc/ssh/moduli` as short as 1024 bit, which, I believe, are not considered relevant for use nowadays.

Is there any reason not to advice to remove the groups whose modulo is shorter than 2048 bits (or even 3072 bits, with the latter for modern configuration, the former for intermediate) ?

**Comment by floatingatoll** [comment]
Hi David,

I did my best to translate this into a request and it sounds like you're
asking us to provide guidance on OpenSSH moduli configuration. Is that an
accurate summary of your request below?

**Comment by David-5-1** [comment]
Hi floatingatoll,

you can summarize my post as you did (it will probably have the same result) but I was more asking if there was a reason why there was no guidance on moduli configuration.

**Comment by floatingatoll** [comment]
I'm hesitant to lead with a post-mortem in this instance. Users will
benefit from focusing on he improvement itself first. I'm tentatively
assuming anyways this was either a time prioritization choice, or just
simple oversight. There are hundreds of options with a security impact
across all of the products covered here and we depend critically on
feedback to decide what to consider next.

Thank you for your proposal!

**Comment by David-5-1** [comment]
I may not have been clear, my point was to let people oppose the addition of some guidance on moduli configuration if there was reasons why it would be useless (although I don't see any). Otherwise, I agree with you that there would be probably little gain on investigating why there was nothing about this and adding some explanations would be more efficient in helping people secure servers.

**Comment by David-5-1** [comment]
Follow-up here : https://github.com/mozilla/wikimo_content/pull/76

**Comment by gdestuynder** [comment]
i believe this is fixed by #76
